--ozone-platform=wayland
--ozone-platform-hint=wayland
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,VaapiOnNvidiaGPUs,VaapiIgnoreDriverChecks
--enable-hardware-overlays=single-fullscreen,single-on-top,underlay
--disable-features=HDRSupport,InfiniteSessionRestore,WaylandWpColorManagerV1,UseChromeOSDirectVideoDecoder
--enable-zero-copy
--ignore-gpu-blocklist
