--ozone-platform=wayland
--ozone-platform-hint=wayland
--ignore-gpu-blocklist
--enable-features=AcceleratedVideoDecodeLinuxGL,VaapiOnNvidiaGPUs,VaapiIgnoreDriverChecks
--disable-features=HDRSupport,InfiniteSessionRestore,WaylandWpColorManagerV1,UseChromeOSDirectVideoDecoder,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
