return {
	-- pack = { src = "https://github.com/zbirenbaum/copilot.lua" },
	-- config = function()
	-- 	require("copilot").setup({
	-- 		panel = { enabled = false },
	-- 		suggestion = {
	-- 			auto_trigger = true,
	-- 			hide_during_completion = true,
	-- 		},
	-- 		filetypes = {
	-- 			markdown = true,
	-- 			help = true,
	-- 		},
	-- 		copilot_model = "gpt-4o-copilot",
	-- 		server = {
	-- 			type = "binary",
	-- 		},
	-- 	})
	-- 	vim.cmd("Copilot disable")
	-- end,
}
