return {
	pack = { src = "https://github.com/onsails/lspkind.nvim" },
	config = function()
		require("lspkind").init({
			symbol_map = {
				Namespace = "󰌗",
				Text = "󰉿",
				Method = "󰆧",
				Function = "󰆧",
				Constructor = "",
				Field = "󰜢",
				Variable = "󰀫",
				Class = "󰠱",
				Interface = "",
				Module = "",
				Property = "󰜢",
				Unit = "󰑭",
				Value = "󰎠",
				Enum = "",
				Keyword = "󰌋",
				Snippet = "",
				Color = "󱓻",
				File = "󰈚",
				Reference = "󰈇",
				Folder = "󰉋",
				EnumMember = "",
				Constant = "󰏿",
				Struct = "󰙅",
				Event = "",
				Operator = "󰆕",
				TypeParameter = "󰊄",
				Table = "",
				Object = "󰅩",
				Tag = "",
				Array = "[]",
				Boolean = "",
				Number = "",
				Null = "󰟢",
				Supermaven = "",
				String = "󰉿",
				Calendar = "",
				Watch = "󰥔",
				Package = "",
				Copilot = "",
				Codeium = "",
				TabNine = "",
				BladeNav = "",
			},
		})
	end,
}
