return {
	-- {
	-- 	"gelguy/wilder.nvim",
	-- 	keys = { ":", "/", "?" },
	-- 	config = function()
	-- 		local wilder = require("wilder")
	-- 		local pine = require("rose-pine.palette")
	--
	-- 		local text_highlight = wilder.make_hl("WilderText", { { a = 1 }, { a = 1 }, { foreground = pine.text } })
	-- 		local accent_highlight =
	-- 			wilder.make_hl("WilderAccent", { { a = 1 }, { a = 1 }, { foreground = pine.rose } })
	--
	-- 		wilder.setup({ modes = { ":", "/", "?" } })
	--
	-- 		wilder.set_option("pipeline", {
	-- 			wilder.branch(wilder.cmdline_pipeline({ fuzzy = 1 }), wilder.vim_search_pipeline({ fuzzy = 1 })),
	-- 		})
	--
	-- 		wilder.set_option(
	-- 			"renderer",
	-- 			wilder.popupmenu_renderer(wilder.popupmenu_border_theme({
	-- 				highlighter = wilder.basic_highlighter(),
	-- 				highlights = {
	-- 					default = text_highlight,
	-- 					border = accent_highlight,
	-- 					accent = accent_highlight,
	-- 				},
	-- 				pumblend = 5,
	-- 				min_width = "100%",
	-- 				min_height = "25%",
	-- 				max_height = "25%",
	-- 				border = "rounded",
	-- 				left = { " ", wilder.popupmenu_devicons() },
	-- 				right = { " ", wilder.popupmenu_scrollbar() },
	-- 			}))
	-- 		)
	-- 	end,
	-- },
}
