# Nushell Config
$env.config.show_banner = false

# Modular configs
source paths.nu
source aliases.nu

# Tool integrations (generated by env.nu before this file is parsed)
source ~/.cache/nushell/mise-init.nu
source ~/.cache/nushell/zoxide-init.nu
source ~/.cache/nushell/jj-completions.nu

# Custom commands
source share.nu
source transcode.nu
source krc.nu
source try.nu
source work.nu
