# Nushell Config
$env.config.show_banner = false

# SSH Agent
source login.nu

# Tool integrations (generated by env.nu before this file is parsed)
source ~/.cache/nushell/mise-init.nu

# Modular configs
source scripts/prompt.nu
source scripts/aliases.nu
source scripts/dot-completions.nu
source ~/.cache/nushell/zoxide-init.nu
source ~/.cache/nushell/jj-completions.nu

# Custom commands
source scripts/share.nu
source scripts/transcode.nu
source scripts/krc.nu
