start-at-login = true
after-startup-command = ["exec-and-forget sketchybar"]
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 90
exec-on-workspace-change = ["/bin/bash", "-c", "sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"]

[mode.main.binding]
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"

cmd-shift-backtick = "reload-config"

[mode.resize.binding]
h = "resize width -50"
j = "resize height +50"
k = "resize height -50"
l = "resize width +50"
enter = "mode main"
esc = "mode main"

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 10
outer.right = 10
outer.top = 10
outer.bottom = 10

[[on-window-detected]]
if.app-id = "com.google.Chrome"
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "com.hnc.Discord"
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = "move-node-to-workspace 2"
