#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_border                off
yabai -m config active_window_border_color   0xff008bff
yabai -m config normal_window_border_color   0x01000000
yabai -m config window_border_width          8
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off
yabai -m config window_shadow		     off

# general space settings
yabai -m config layout                       stack
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8
yabai -m config external_bar main:8:60

# Fullscreen stacking focus
yabai -m window --focus stack.first
yabai -m window --focus stack.prev
yabai -m window --focus stack.next
yabai -m window --focus stack.recent
yabai -m window --focus stack.last

# space 2: code
yabai -m space 2 --layout bsp
yabai -m rule --add app="Code" space=^2
yabai -m rule --add app="kitty" space=^2

# space 1: web
yabai -m rule --add app="Firefox Developer Edition" space=^1
yabai -m rule --add app="Discord" space=^1

# space 3: docs
yabai -m rule --add app="Dash" space=^3
yabai -m rule --add app="TickTick" space=^3
yabai -m rule --add app="Linear" space=^3

# space 4: music
yabai -m rule --add app="Spotify" space=^4

# things which create floating children
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="Activity Monitor" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add title="JetBrains Toolbox" manage=off
yabai -m rule --add label="System Preferences" app="System Preferences" title=".*" manage=off
yabai -m rule --add app="Loom" manage=off
yabai -m rule --add app="Sleeve" manage=off