alias cl='clear'
alias ..='cd ..'
alias cat='bat'
alias cd='z'
alias vim='nvim'
alias vi='nvim'
alias ls='eza -lh --group-directories-first --icons=auto'
alias lt='eza --tree --level=2 --long --icons --git'
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
alias oc='opencode'
