set -gx XDG_CACHE_HOME $HOME/.cache
set -gx XDG_CONFIG_HOME $HOME/.config
set -gx XDG_DATA_HOME $HOME/.local/share
set -gx XDG_STATE_HOME $HOME/.local/state
set -gx EDITOR nvim
set -gx SUDO_EDITOR nvim
set -gx GPG_TTY (tty)
set -gx JJ_CONFIG $XDG_CONFIG_HOME/jj/config.toml
set -gx RIPGREP_CONFIG_PATH $XDG_CONFIG_HOME/ripgrep/config
set -gx BAT_THEME ansi
