# All game launchers go to workspace 4 by default
windowrule = workspace 4, match:class ^steam$
windowrule = workspace 4, match:title ^Steam$
windowrule = workspace 4, match:title ^Battle\.net$
windowrule = workspace 4, match:class ^net\.lutris\.Lutris$

# Steam game windows and cs2 go to workspace 5
windowrule = workspace 5, match:class ^(steam_app_([0-9]+|default)|cs2)$
windowrule = fullscreen on, match:class ^(steam_app_([0-9]+|default)|cs2)$
windowrule = opacity 1 1, match:class ^(steam_app_([0-9]+|default)|cs2)$
windowrule = stay_focused on, match:class ^(steam_app_([0-9]+|default)|cs2)$

# Battle.net
windowrule = workspace 4, match:title ^Battle\.net$
windowrule = float on, match:title (Battle.net)
windowrule = center on, match:title (Battle.net)
windowrule = opacity 1 1, match:title (Battle.net)
windowrule = size 1600 1200, match:title (Battle.net)
