gui:
  authorColors:
    "*": magenta
  promptToReturnFromSubprocess: false
  showBottomLine: true
  showCommandLog: false
  showListFooter: true
  skipRewordInEditorWarning: true
  theme:
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - reverse
