gui:
  promptToReturnFromSubprocess: false
  showBottomLine: true
  showCommandLog: true
  showListFooter: true
  skipRewordInEditorWarning: true
  theme:
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - reverse
git:
  disableForcePushing: true
