gui:
  authorColors:
    "*": magenta
  promptToReturnFromSubprocess: false
  showBottomLine: false
  showCommandLog: false
  showListFooter: false
  skipRewordInEditorWarning: true
  theme:
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - reverse
