return {
	pack = { src = "https://github.com/tjdevries/colorbuddy.nvim" },
	config = function()
		local colorbuddy = require("colorbuddy")
		colorbuddy.colorscheme("personal")

		local Color = colorbuddy.Color
		local Group = colorbuddy.Group
		local colors = colorbuddy.colors
		local groups = colorbuddy.groups
		local styles = colorbuddy.styles

		Color.new("bg0", "#141824")
		Color.new("bg1", "#080b14")
		Color.new("bg2", "#12182b")
		Color.new("bg3", "#151b2e")
		Color.new("bg4", "#1c2748")
		Color.new("fg", "#cbcebc")
		Color.new("fg_dim", "#87919d")
		Color.new("line_nr", "#3b4450")
		Color.new("comment", "#87919d")
		Color.new("cursor", "#26b2b2")
		Color.new("cursor_line", "#1c2748")
		Color.new("selection", "#1a3c49")
		Color.new("split", "#21333f")

		Color.new("kw", "#f07178")
		Color.new("ty", "#ffa759")
		Color.new("val", "#ff6a27")
		Color.new("fn", "#ffcc66")
		Color.new("str", "#bae67e")
		Color.new("num", "#9dd2bb")
		Color.new("yellow", "#e4d97d")
		Color.new("warn", "#f8ad34")
		Color.new("note", "#e0ad82")
		Color.new("blue", "#309ecb")
		Color.new("cyan", "#26b2b2")
		Color.new("cyan_bright", "#33cccc")
		Color.new("teal", "#599999")
		Color.new("error", "#ff0000")
		Color.new("add", "#33b333")
		Color.new("delete", "#e64d4d")

		Group.new("Normal", colors.fg, colors.bg0)
		Group.new("NormalNC", colors.fg_dim, colors.bg0)
		Group.new("NormalFloat", colors.fg, colors.bg1)
		Group.new("FloatBorder", colors.split, colors.bg1)
		Group.new("FloatTitle", colors.ty, colors.bg1, styles.bold)

		Group.new("Cursor", colors.bg0, colors.cursor)
		Group.new("lCursor", colors.bg0, colors.cursor)
		Group.new("TermCursor", colors.bg0, colors.cursor)
		Group.new("CursorLine", nil, colors.cursor_line)
		Group.new("CursorColumn", nil, colors.cursor_line)
		Group.new("ColorColumn", nil, colors.bg3)
		Group.new("LineNr", colors.line_nr, colors.bg0)
		Group.new("CursorLineNr", colors.fg_dim, colors.bg0)
		Group.new("SignColumn", colors.line_nr, colors.bg0)
		Group.new("FoldColumn", colors.line_nr, colors.bg0)
		Group.new("Folded", colors.fg_dim, colors.bg2)
		Group.new("VertSplit", colors.split, colors.bg0)
		Group.new("WinSeparator", colors.split, colors.bg0)
		Group.new("EndOfBuffer", colors.line_nr, colors.bg0)

		Group.new("Visual", nil, colors.selection)
		Group.new("VisualNOS", nil, colors.selection)
		Group.new("Search", colors.bg0, colors.yellow, styles.bold)
		Group.new("IncSearch", colors.bg0, colors.warn, styles.bold)
		Group.new("CurSearch", colors.bg0, colors.warn, styles.bold)
		Group.new("MatchParen", colors.bg0, colors.cyan_bright, styles.bold)

		Group.new("Pmenu", colors.fg, colors.bg2)
		Group.new("PmenuSel", colors.bg0, colors.cyan_bright, styles.bold)
		Group.new("PmenuSbar", nil, colors.bg2)
		Group.new("PmenuThumb", nil, colors.blue)
		Group.new("WildMenu", colors.bg0, colors.cyan_bright, styles.bold)

		Group.new("StatusLine", colors.fg, colors.bg2)
		Group.new("StatusLineNC", colors.fg_dim, colors.bg1)
		Group.new("TabLine", colors.fg_dim, colors.bg1)
		Group.new("TabLineSel", colors.fg, colors.bg3, styles.bold)
		Group.new("TabLineFill", colors.fg_dim, colors.bg1)

		Group.new("Title", colors.ty, nil, styles.bold)
		Group.new("Directory", colors.blue)
		Group.new("Question", colors.str)
		Group.new("NonText", colors.fg_dim)
		Group.new("Whitespace", colors.fg_dim)
		Group.new("SpecialKey", colors.fg_dim)
		Group.new("Conceal", colors.teal)

		Group.new("Comment", colors.comment, nil, styles.italic)
		Group.new("Constant", colors.val)
		Group.new("String", colors.str)
		Group.new("Character", colors.str)
		Group.new("Number", colors.num)
		Group.new("Boolean", colors.val)
		Group.new("Float", colors.num)

		Group.new("Identifier", colors.fg)
		Group.new("Function", colors.fn)
		Group.new("Statement", colors.kw)
		Group.new("Conditional", colors.kw)
		Group.new("Repeat", colors.kw)
		Group.new("Label", colors.ty)
		Group.new("Operator", colors.kw)
		Group.new("Keyword", colors.kw)
		Group.new("Exception", colors.note)

		Group.new("PreProc", colors.ty)
		Group.new("Include", colors.ty)
		Group.new("Define", colors.ty)
		Group.new("Macro", colors.note)
		Group.new("PreCondit", colors.ty)

		Group.new("Type", colors.ty)
		Group.new("StorageClass", colors.ty)
		Group.new("Structure", colors.ty)
		Group.new("Typedef", colors.ty)

		Group.new("Special", colors.note)
		Group.new("SpecialChar", colors.note)
		Group.new("Tag", colors.blue)
		Group.new("Delimiter", colors.fg)
		Group.new("SpecialComment", colors.note)
		Group.new("Debug", colors.error)

		Group.new("Underlined", colors.blue, nil, styles.underline)
		Group.new("Bold", nil, nil, styles.bold)
		Group.new("Italic", nil, nil, styles.italic)

		Group.new("Error", colors.error, colors.bg0, styles.bold)
		Group.new("ErrorMsg", colors.error, colors.bg0, styles.bold)
		Group.new("WarningMsg", colors.warn, colors.bg0, styles.bold)
		Group.new("ModeMsg", colors.cyan)
		Group.new("MoreMsg", colors.str)
		Group.new("Todo", colors.bg0, colors.note, styles.bold)

		Group.new("DiagnosticError", colors.error)
		Group.new("DiagnosticWarn", colors.warn)
		Group.new("DiagnosticInfo", colors.blue)
		Group.new("DiagnosticHint", colors.cyan)
		Group.new("DiagnosticOk", colors.str)
		Group.new("DiagnosticVirtualTextError", colors.kw)
		Group.new("DiagnosticVirtualTextWarn", colors.yellow)
		Group.new("DiagnosticVirtualTextInfo", colors.blue)
		Group.new("DiagnosticVirtualTextHint", colors.teal)
		Group.new("DiagnosticUnderlineError", nil, nil, styles.undercurl, colors.error)
		Group.new("DiagnosticUnderlineWarn", nil, nil, styles.undercurl, colors.warn)
		Group.new("DiagnosticUnderlineInfo", nil, nil, styles.undercurl, colors.blue)
		Group.new("DiagnosticUnderlineHint", nil, nil, styles.undercurl, colors.cyan)

		Group.new("DiffAdd", colors.add, colors.bg2)
		Group.new("DiffChange", colors.blue, colors.bg2)
		Group.new("DiffDelete", colors.delete, colors.bg2)
		Group.new("DiffText", colors.fn, colors.bg3, styles.bold)

		Group.new("Added", colors.add)
		Group.new("Changed", colors.blue)
		Group.new("Removed", colors.delete)

		Group.new("gitcommitBranch", colors.cyan)
		Group.new("gitcommitUntracked", colors.yellow)
		Group.new("gitcommitSelected", colors.str)
		Group.new("gitcommitDiscarded", colors.kw)

		Group.new("@comment", groups.Comment)
		Group.new("@comment.documentation", colors.note)
		Group.new("@error", groups.Error)
		Group.new("@warning", groups.WarningMsg)
		Group.new("@none", colors.fg)
		Group.new("@preproc", groups.PreProc)
		Group.new("@define", groups.Define)
		Group.new("@operator", groups.Operator)

		Group.new("@punctuation", colors.fg)
		Group.new("@punctuation.delimiter", colors.fg)
		Group.new("@punctuation.bracket", colors.fg)
		Group.new("@punctuation.special", colors.kw)

		Group.new("@string", groups.String)
		Group.new("@string.documentation", colors.note)
		Group.new("@string.regex", colors.yellow)
		Group.new("@string.regexp", colors.yellow)
		Group.new("@string.escape", colors.note)
		Group.new("@string.special", colors.note)
		Group.new("@string.special.symbol", colors.fg)

		Group.new("@character", groups.Character)
		Group.new("@character.special", colors.note)
		Group.new("@boolean", groups.Boolean)
		Group.new("@number", groups.Number)
		Group.new("@number.float", groups.Float)

		Group.new("@function", groups.Function)
		Group.new("@function.call", groups.Function)
		Group.new("@function.method", groups.Function)
		Group.new("@function.method.call", groups.Function)
		Group.new("@function.builtin", colors.note)
		Group.new("@function.macro", colors.note)

		Group.new("@method", groups.Function)
		Group.new("@method.call", groups.Function)
		Group.new("@constructor", colors.ty)
		Group.new("@parameter", colors.fg)
		Group.new("@parameter.reference", colors.fg)
		Group.new("@parameter.builtin", colors.num)

		Group.new("@keyword", groups.Keyword)
		Group.new("@keyword.function", colors.kw)
		Group.new("@keyword.operator", colors.kw)
		Group.new("@keyword.return", colors.kw)
		Group.new("@keyword.conditional", colors.kw)
		Group.new("@keyword.repeat", colors.kw)
		Group.new("@keyword.exception", colors.kw)
		Group.new("@keyword.import", colors.ty)
		Group.new("@keyword.directive", colors.ty)
		Group.new("@keyword.directive.define", colors.ty)
		Group.new("@keyword.type", colors.ty)
		Group.new("@keyword.modifier", colors.ty)

		Group.new("@conditional", groups.Conditional)
		Group.new("@repeat", groups.Repeat)
		Group.new("@label", groups.Label)
		Group.new("@include", groups.Include)
		Group.new("@exception", groups.Exception)

		Group.new("@type", groups.Type)
		Group.new("@type.builtin", colors.ty)
		Group.new("@type.qualifier", colors.kw)
		Group.new("@type.definition", colors.ty)
		Group.new("@storageclass", groups.StorageClass)
		Group.new("@attribute", colors.ty)
		Group.new("@field", colors.fg)
		Group.new("@property", colors.fg)

		Group.new("@constant", groups.Constant)
		Group.new("@constant.builtin", colors.num)
		Group.new("@constant.macro", colors.note)
		Group.new("@module", colors.fg)
		Group.new("@module.builtin", colors.num)
		Group.new("@variable", groups.Identifier)
		Group.new("@variable.builtin", colors.num)
		Group.new("@variable.parameter", colors.fg)
		Group.new("@variable.member", colors.fg)

		Group.new("@markup", colors.fg)
		Group.new("@markup.strong", colors.fg, nil, styles.bold)
		Group.new("@markup.italic", colors.fg, nil, styles.italic)
		Group.new("@markup.underline", colors.fg, nil, styles.underline)
		Group.new("@markup.strikethrough", colors.fg_dim, nil, styles.strikethrough)
		Group.new("@markup.heading", colors.ty, nil, styles.bold)
		Group.new("@markup.heading.1", colors.ty, nil, styles.bold)
		Group.new("@markup.heading.2", colors.note, nil, styles.bold)
		Group.new("@markup.heading.3", colors.note, nil, styles.bold)
		Group.new("@markup.heading.4", colors.note, nil, styles.bold)
		Group.new("@markup.heading.5", colors.note, nil, styles.bold)
		Group.new("@markup.heading.6", colors.note, nil, styles.bold)
		Group.new("@markup.raw", colors.str)
		Group.new("@markup.link", colors.blue, nil, styles.underline)
		Group.new("@markup.math", colors.yellow)
		Group.new("@markup.link.label", colors.teal)
		Group.new("@markup.link.url", colors.blue, nil, styles.underline)

		Group.new("@text", groups["@markup"])
		Group.new("@text.strong", groups["@markup.strong"])
		Group.new("@text.emphasis", groups["@markup.italic"])
		Group.new("@text.underline", groups["@markup.underline"])
		Group.new("@text.strike", groups["@markup.strikethrough"])
		Group.new("@text.title", groups["@markup.heading"])
		Group.new("@text.literal", groups["@markup.raw"])
		Group.new("@text.uri", groups["@markup.link.url"])
		Group.new("@text.math", groups["@markup.math"])
		Group.new("@text.reference", groups["@markup.link.label"])
		Group.new("@text.environment", colors.ty)
		Group.new("@text.environment.name", colors.note)

		Group.new("@tag", colors.blue)
		Group.new("@tag.attribute", colors.ty)
		Group.new("@tag.delimiter", colors.fg)

		Group.new("@lsp.type.namespace", groups["@module"])
		Group.new("@lsp.type.type", groups["@type"])
		Group.new("@lsp.type.class", groups["@type"])
		Group.new("@lsp.type.enum", groups["@type"])
		Group.new("@lsp.type.interface", groups["@type"])
		Group.new("@lsp.type.struct", groups["@type"])
		Group.new("@lsp.type.typeParameter", groups["@type.definition"])
		Group.new("@lsp.type.parameter", groups["@parameter"])
		Group.new("@lsp.type.variable", groups["@variable"])
		Group.new("@lsp.type.property", groups["@property"])
		Group.new("@lsp.type.enumMember", groups["@constant"])
		Group.new("@lsp.type.function", groups["@function"])
		Group.new("@lsp.type.method", groups["@function.method"])
		Group.new("@lsp.type.macro", groups["@function.macro"])
		Group.new("@lsp.type.keyword", groups["@keyword"])
		Group.new("@lsp.type.comment", groups["@comment"])
		Group.new("@lsp.type.string", groups["@string"])
		Group.new("@lsp.type.number", groups["@number"])
		Group.new("@lsp.type.operator", groups["@operator"])

		Group.new("@lsp.typemod.variable.defaultLibrary", groups["@variable.builtin"])
		Group.new("@lsp.typemod.function.defaultLibrary", groups["@function.builtin"])
		Group.new("@lsp.typemod.method.defaultLibrary", groups["@function.builtin"])
		Group.new("@lsp.typemod.variable.readonly", groups["@constant"])
		Group.new("@lsp.typemod.variable.constant", groups["@constant"])
		Group.new("@lsp.typemod.property.readonly", groups["@property"])
		Group.new("@lsp.mod.variable.ruby.readonly", groups["@constant"])
		Group.new("@lsp.mod.variable.ruby.constant", groups["@constant"])
		Group.new("@lsp.mod.method.ruby.defaultLibrary", groups["@function.builtin"])
		Group.new("@lsp.mod.function.ruby.defaultLibrary", groups["@function.builtin"])

		Group.new("@lsp.typemod.variable.readonly.ruby", groups["@variable"])
		Group.new("@lsp.typemod.variable.constant.ruby", groups["@variable"])
		Group.new("@lsp.typemod.property.readonly.ruby", groups["@property"])
		Group.new("@lsp.typemod.property.defaultLibrary.ruby", groups["@property"])
		Group.new("@lsp.typemod.property.constant.ruby", groups["@property"])
		Group.new("@lsp.typemod.method.defaultLibrary.ruby", groups["@function.builtin"])
		Group.new("@lsp.typemod.function.defaultLibrary.ruby", groups["@function.builtin"])
		Group.new("@lsp.typemod.parameter.readonly.ruby", groups["@parameter"])
		Group.new("@lsp.typemod.parameter.constant.ruby", groups["@parameter"])

		vim.g.terminal_color_0 = "#080b14"
		vim.g.terminal_color_1 = "#f07178"
		vim.g.terminal_color_2 = "#bae67e"
		vim.g.terminal_color_3 = "#e4d97d"
		vim.g.terminal_color_4 = "#309ecb"
		vim.g.terminal_color_5 = "#ffa759"
		vim.g.terminal_color_6 = "#26b2b2"
		vim.g.terminal_color_7 = "#cbcebc"
		vim.g.terminal_color_8 = "#87919d"
		vim.g.terminal_color_9 = "#ff0000"
		vim.g.terminal_color_10 = "#9dd2bb"
		vim.g.terminal_color_11 = "#f8ad34"
		vim.g.terminal_color_12 = "#599999"
		vim.g.terminal_color_13 = "#ffcc66"
		vim.g.terminal_color_14 = "#33cccc"
		vim.g.terminal_color_15 = "#ffffff"
	end,
}
