[tools]
ruby = "3.4.5"
nodejs = ["latest", "22.14.0"]
zig = "latest"
rust = "latest"
golang = "1.24.0"
ocaml = "5.3.0"
opam = "2.3.0"
gleam = "1.10.0"
erlang = "27.3.3"
go = "1.24.2"
node = "latest"
bun = "latest"

[settings]
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = "1 week"
not_found_auto_install = true
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
